spring.application.name=aquaica
spring.datasource.url=jdbc:postgresql://localhost:5436/aquaica
spring.datasource.username=postgres
spring.datasource.password=RAMIROpp20//

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework.security=DEBUG